language: ruby
# only run CI-builds on master branch
branches:
  only:
  - source
rvm:
- 2.4.0
before_install:
  - rvm install 2.4.0
install:
  - bundle install
  - npm install
# set execution permission on our build script
before_script:
 - chmod +x ./script/cibuild
 - gulp build-clean --production
# path to our build script.
# Travis will run `bundle install` by default before running our script
script: ./script/cibuild
exclude: [vendor]
sudo: false
