language: ruby
rvm:
- 2.4.0
install:
- gem install jekyll
script:
- bundle install
- bundle exec jekyll build
- rake test
after_success:
- git clone https://$GITHUB_REPO
- cd $(basename ${GITHUB_REPO%.git})
- git config user.name "Travis CI"
- git config user.email ${EMAIL}
- rsync -az --delete --exclude '.git*' ../_site/ .
- touch .nojekyll
- git add -A .
- git commit -m "Generated Jekyll site by Travis CI - ${TRAVIS_BUILD_NUMBER}"
- git push --force "https://user:${GH_TOKEN}@${GITHUB_REPO}" HEAD:${REPO_TARGET_BRANCH}

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GITHUB_REPO: github.com/vcaldas/vcaldas.github.io
  - REPO_TARGET_BRANCH: master
  - secure: v2b/jkcUJZASP6hhFMi/bR5OGYxO2Hkn5UZDlI+pxbmsAThEDKfuQbGpBwV+Pq2YwKkJ09anAZbwRHoT58m56hRigBkv0qdWh1esE5k/4cnEHquXGIczTuHUbBGrm5XXU+0pqmcUMMXjOiEEeEPBlgcaL8WFnz+a5v1hPGl1lrGyQYqWgWl6z/PGyzH35paCEUx2+L72gA8z4FhsAz3OlSLjgUp+Pcv0ZwAEEMCsLpJbq6SGFNGgXWLQDRMnRBb1ikq5qByb3zI1gHqqJY5mu1nRAMMINIHSzogn0SSGXCiju11JKD6VwU3cP74be8NIlFF1yPMU2h0JSVq7DIRxk+7OT4EiackiYAZ91LiWc4S5VCFh4Orv9FjdF7bRSKh+eGNKinjpNHQodhzZw/jv8PicgHA3KMjOtD8cEdfrJgZBAS+LMIBjETKz0CHuxDl80cRRXxcmO4PYYOIPm2esIXw9aEZvFvLtKWaioo+gzqLWLZ6TY1Fb+z6SkxIVMUQL0squrUw/1a+qVx48kCfwkWCKwvNHhUwLDTxbxlgOTK09oo9E7NzEU+EthpNp81BdBict4g8gN6BJk47USwAP3TEI6V/lirtzBC+z3PhZ3srs2CmL4pKHR6lezifeWAKwbDgQpH8+oaxdYy2ODnCUuB8ebPnVzqK9E2MxoAQ38GY=
  - secure: bX1Q3MuU3FzPd1/w7JK6TkznhI+G0q4PKZcif5l4plxuRYT+5lHUzYqFzPrZXRSEwMl5ad9rVSAfi4jNqXsbRBTPYLGrtXb+xHKodQyqmMOYcnRIdHnvuC6pdiByQWlynUnGbbJtefgTi8lJ9zTIjcgIIGWyIgHLQVzN4RRfywoS+CRU/Ka1eV1yFg5Frkn4LCHAEIoFEs/1kph30B2pQU74wUcO9a2BJ6d0IsDTXWCCcyFPeRKLGV120Bqz/vHNXDA7yNQgXVD6MLCnEsBM+oBOBXtF/p5IDoBsgHyugJD1jxjBxmpnjiK18KympsAq09PVUAx2jzatFThgU86nP2Zo1nwkWmQl0NhQCzVU+3Tm3axDbYL68jglZz76hCkjMPjyJw0Ktbs7LdY+MMX7KvmyJduv7Wf4Eg6MsXl72xhlxf21PXuMiiv9kTFe9ZqsyHDZgsPX/NFeAN5M2K7f6o+swMJwxYPfu4BlCbbofIawEtzb/L0JCWEw1SbOOETFytLJAbARYYtSyzqBHpqkdv6Fn2NumWE2iVOupBeveAe6qp592xiNXBhcm/vw/sPs3zfF1Tursmo5EedFSAdEw9oMCMDBWOxRKTmAuqAKABRZT76w5NVAClm6Qd8EHI8jo5T71viaOHlCO3mSg67LRzjf9jMnqmhwYwrDNj04Jkk=
  - secure: bvbNjlOi9+1jxJe+oYHcQy26zT9J2kf5HQzWNXjz4Bi7KimImT8d16rmnHAPEo0R4lxZCWNQD6uQpSBVOegkqAnhiCRWQgxB+sMMecwdWS0qxoWsfwak+NILg/sb5u82yZtoVFhmE2CVhWsrW6VX3X6HfOErvFoyWVnkrBE1kH4GnYlYx9IpNuRQ+29xz7mevwkYDgqStZColH9NCJfZxbiTxsRsdYqXowV4L7UZ3iT/3RLF2Q/k3Rxm07cB+y9BYleJkYjjwhGTOKqPJklX6YqRDEPrvZh/5vglafX1uzFNSG9TMQIedd0KiLUnie8fZdzp1T/0u96A17MTzWVRUi0I2eqtdGYtMlk4nFk+bOSELxPVyfXdqV/Y5dcRknsw6A4gIkWSGbXvEHLLonB4bY0wTmx+uiHuA13S0sVaDUJhdObhJPq7zJr+z0Y+h//Q9AFuQzZK/+YR4npYE/7zlrzlmOSTNNlM50/W/WbJw8o/pWHIFQ7jyWCXKQV7EgFAL8eD8Cot54lvdAcVdT/S0XWBiE21Wq08ZdDyfl31sNTCICzPDxiRiD8092Z1dm5jqo9UJqyDm+AN8mYhgLa86Kufx1Q8e7/44QSOL5DS7j3S03iYyrm5KYGMVxPo12M27+ircpyPJ4AGoZzIUqGD9fZKY46+kahQVGKVmPz6n9Y=
