
language: node_js
sudo: required
script:
  - ./_scripts/run-tests.sh
branches:
  except:
  - master
node_js:
 - '6.1'
before_install:
  - if [[ `npm -v` != 4* ]]; then npm i -g npm@4; fi
  - rvm install 2.1
  - rvm use 2.1
  - . $HOME/.nvm/nvm.sh && nvm install 6 && nvm use 6.1
  - gem install bundler
  - bundle check || bundle install
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: FiCv6oodPPXKDGXmkbb3H2/aetQ5T4NtDW0xlB6jnmTVULupWy/z22TQMkr+Sa5ITifqCmA7CBu034NZUkCrPvUsDZBNx1SWDyuN3/PqvKhe7/V7qLLcjqBOPm2doohPbLnjY2DCJWKRr16ZE0OfsHpHLmDXRDXACUx6ElC2Ttq4zGYEOdnSCvLTv9I/o162ECo9ek5jM0cbovrBW6OmGrdVhJQvgCfAiY+YzmQwRzYQ1Q72zakgDLt+jS/IuB+7wHtfTUtNPd29smF6GyaSI+M5jGt1TqlS+zHU3DS6m1rnHAYkPQOvJh+B11HXD8aUwLMCfRxp+XDOiCDttaz+nFdDtC5IFzsruTxczSjZKo/GgDzO2LsEGLEFz+Z/WyGGLc5mW2mkAlO/EyV0WgiHJTO1IsYAAeKaL0/hyGUz7Y14KlgvPw1osY/UKVOVLk+xWSJZvI9piayjlX79ZCZjfcLj6EIGHejq58G4rEtwl/mQXNa+o1P0KJXtZl6ja+Ks9fdcgKLfWCm/JgCRdy6K9nTrYQeb43ANVxuw6WV79Toa6prChPpGMm0FwDaG5D4PmYO+SdYnty+xHJWNxpLtaHfJlU0KTdAfwNfATbcgZjPXIJSm6cA8ivtA4bUBJRSOjkoxN3EqTDYYwggTSY7QO/dDbwBiZ5Siz/CnIPOO6pA=
  - secure: WE4ppnJZvhihyoJ0NEs1mhtkbmLORPKJeRB2xob+Mn/bvWzVuW3CQBOAFs4pLj1kM4F138lCplLFvaFoAbIkZyfqHCIS31LqYO9RQ5zJ3m1P+qMNvE/RODz1OT+6fNNKNsJLdM3MV/XdU3fj283yzavOIKcYBLlssuGJqi2dEooOQSZUJ4FObmVawSimZhOIjyUVBj7rSijBGXWlfrEjoku/VeYW5gBLOraD13Y4WQtxfcxt232RjrIgvyReSutOLsiO18rs5TehsiislxZe2Fj/rbNX4h9dfsjjPi84TeLXKVgMMJkZZeHAmI0rAWuKAm9HMJ2+SVj/mBns/pgYJSDuGgvCzbzvudTaEhtZkqcNujyxVB8KgnIGWKuGWxe3PRUtHzCZRIyoJ0WxT4ZV3LIBCjRSYAwZkFAxs1TN63nhyibvHEHWZACMtlAcv8W41Kj3lddDJvzz9xK2xLA2jJOW044mYN+256hYqbmlbPIIshXJFusBc5NgwQ+osNEKHTMyqPyNFmSGaRuf2scXjERS1xox8Yw6npxJbkymOPg70/ieG8FIL3OrTDgCGjxLB255fWS8OGyFlTdYCke4DRDppuTZHyCCJ9gBtJFpv4Utcqqr8rUILvBQsn4vAgKjKJzkouwnUeZO4wuNsTjCiV62ktMvQOdA8EjsckLGTLM=
deploy:
  provider: script
  script: "./_scripts/build.sh"
  skip_cleanup: false
  on:
    branch: source
