language: node_js
branches:
  only:
  - source
node_js:
- '7'
before_install:
- rvm install 2.4.0
before_script:
- npm i -g gulp-cli
- npm install
- gem install bundler
- bundle install
script:
- gulp build-clean  --production
after_success:
- git clone https://$GITHUB_REPO
- git branch
- cd $(basename ${GITHUB_REPO%.git})
- git config user.name "Travis CI"
- git config user.email ${EMAIL}
- rsync -az --delete --exclude '.git*' ../_site/ .
- touch .nojekyll
- git add -A .
- git commit -m "Generated Jekyll site by Travis CI - ${TRAVIS_BUILD_NUMBER}"
- git push --force "https://user:${GH_TOKEN}@${GITHUB_REPO}" HEAD:${REPO_TARGET_BRANCH}
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GITHUB_REPO: github.com/vcaldas/vcaldas.github.io
  - REPO_TARGET_BRANCH: master
  - secure: FvW9UD9MIqQVTJ3oODovn+qXPbxeTzgYVTfAjcXJm4bwHVmaDEDOOAHqC8KGuAsyr5bk/E2fSwlm+7U6/GSoH2G/DQAWqjnrgPSDhk/C0udaYvNBIAwwuPGPe/by/VZR5GscPofbYWCZdUeu1xGv4Sx8wROfjhfYxLVOiAABYRP14S4wKYHyWSefBTmoooOLRps+9hqoyi8M25oZrdhIcCaa8tskOCq38FsqwapOnUWlxugm9zGRnbDQ+p3pYQ3mczBgwgoSL9EV1aQMVJxEsO8r8fzP8VHtMoZkU3TSgaNd5LSPBTanvDkTNnkTi9Yn2jPbW35xyHyMNmS6i6MRSwly9CxoRTQXDQyW4fZyec2jYrUcXoWei2eaYZLZbR8eJGZelnW5k26oHacYYTihOkzNf/4eCps5rgSP7tkQmQpSBGQKEywTBWo8PWhGH3U6/XGidN4OGzboCq2VsQ8qHc5P7jyJ/YQJneIIhzXsvBWsHP1gIRnyq+qav9REZFQ6lyTAO0nYmPgFSZwNUTDkb0fFxwnwO6eILJkEwEoZAex7k1dyC8RsZpJHUa79RhzUOLNBP61HlFUorxOngaSSf4yf4qhiD9wu7pLTGe0JQx9cFpVWPK/YjMq82ADge2sbKF2J6mZP/NEQnzQXrMUEMwFIlMwdSgzY1YmYuLpNwww=
  - secure: oy5ivNh4iMV8gprexIOq/KnsstibmOoBiThGkfn6b5/U+SM8URa1IdLT2V2qI/i0/fzgPI1d6lbAFdVGR7ZMEdTqtO6I4OHGZimOQ/MMPkyFNXVEQ+FV+45bpO3xXPODujfJHF462hWCAostLttmWa4RJgkaTp3ECEZcs1u0Pnau7p9qlJsZjPrcaX1q7ywGtOmaVs0xkrxIYtPyCw6Lg46NyPqxUp3SatRUYUGJisHGBbtIvPrklws6MFwCi7l82FLn8V9YJZAerpEJttItiG4vxbKlA1oXNWlZ8Gf+B7XVoFY4ODnfWeXXYDo+fa4JixXvuduZsvbVykazO7NqudENEsWjZ6mjjDhYUmrUmiQARdON9Lz3lXWAowxw3kWExaeLvUtOX60uYGCm/RQ1RaI9H/tr51odLtbS1PfatLzIiKUM1aH7WWOj+Cq3BNdYJMBSTcKZSoGPsEzjqd9ug18CvToVxBsDqsL0/h6CwIzZW3R4x7Wc6BRaOwos3vClxSIYqGbiFIHkOivFzaAomZV4t8HHw3Q6bn6JTtl9xFUvUkEa5NCbFi4wsbJcMFk9D1Y6J1WZqj1OqJkLpcFxcJ+thc8AIVVsOI9B0zHEQD3wuMNGQO18vaBkGW+s6uJa5A7MOu1n9ptkZiCN1rnqXBWSqbfObBNYvj6fZ/kswSo=
