language: node_js
sudo: required
script:
  - ./tests.sh

node_js:
 - '7.4'
before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - npm cache clear
  - gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
  - \curl -sSL https://get.rvm.io | bash -s stable --ruby
  - rvm reload
  - rvm get head --auto-dotfiles
  - rvm install 2.4.0
  - rvm use 2.4.0
  - . $HOME/.nvm/nvm.sh && nvm install 6.1 && nvm use 6.1
  - gem install bundler
  - bundle check || bundle install
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: OR+hW4WjsuN/NfN4m+ADQqgK1FinvZlCGdsMzRtmr58id7w8DMyY4UCi3IfKldzoJCXNBNyIn13F9WU/GhZ4kUeL5JWoEVVDJiFGrwdariFaISzgsprP/X2BlIQFX5rEsf3BMPW6MzvIXYMXKtrunvYbfrIVqoqEfOZAk/o5ThnnCVo/kDWRTFdgrLWwzcn9Hwty8AdsDT5+RR6XzkSBnk0HQ4BRwVYw8Up4pZUZU33GkYsRrHZKHlRP1G+pYyxe18wKhK+O4QJR9TES+QXHF9g62lFR2l7ir5jjx2U5qY18VoJScYmBQaiKG7DHgsTsSEMCHhBIu+7kCwf7aeGV2Wk4oHmck+UOmBcr+i7ZAx1bFHvaS0nKNjX+w989A3RFpIakZyZeqPtPnjAxSf7wBXZDz6DgVQpEYildxTzwPEqi62GHCMAPM2YYl/CVK5qiUNzTA1EctCsUpEZTACoAVN5MBU8dDYdFsdxSlmqwo9aT7pvhQ+WlwAHQ6mrfO2kq/4HBfCDm2MFUAFRb8sc8YDzCvYbk76JFOi7e2h9HzFgYK3QorPd/EvgWTiAC/dO0Qg1kDElURqsDJdtBxvxuaRuji4ImwiIj2BA/6312mUacQns21a+o/cgHO+WdttLZPe+3tOPvpsLa0YoY/UtJI98KY5H84vgYPPnf9deTNnY=
  - secure: AK9+XwjpzXcNxHnWCMzeihMSoS8mWaRdpnk7bVHcBcG+HANhEWrMtswbyV0HoMFAuZT7EpMqjOsNB/QXvwX3yPsoT0uasllNBe4IQTzHtkOsleIwZHipTBixI4gM3H+vf3h0vtPOebwPqJQZqDXxs0oGW6A6xroT7uol2YsvFXyQGB70ODelf5k+9EnHw8CN7UJf7ZpYIAwjkAPt8cxMxtJ6amEpOs3tDoVUEUmarqFhg7n4YbSp57cRVtuiSGbS3nF2DtEpjGQP+6wMN4fH12hDT90mePDmiF3JOg6t/YslYK2YPkHe7ei/iNBFN2j5Q7wIb6yuISWqD8QsnKnbjhKaNscgo16oxMKIgG86Po7Jz5RIdUWeAyk2sS27+W0WEwn5Yv62F36lbCNaWyCTHB1bpcL7LwSFixU2xOxD7oy03XCu2vKtIHmlRNnRO0Bc89JtbRGeasxon2+8uzh1cRc1OaXowsE/CqrDI97GGx3llhzw1/bZsY55ApxSGHiobVtYPg7McW03k9r68QWqyAMNwwqYVxo/m07hiPg3l8TD0zpSRgb/zI+KDNH0tytQsNobYLV6t8fWENykKteoDKeJv8Nb80X7hxt1PZ5ZbqXB4DjfIjzdDarduOhEndzrcRZddWDRR5GbWn1zlkMfnwjWde7b6BFdnIp0NX1s1Ww=
deploy:
  provider: script
  script: "./build.sh"
  skip_cleanup: false
  on:
    branch: source
