language: node_js
# only run CI-builds on master branch
branches:
  only:
  - source

node_js:
  - "7"

before_install:
  - rvm install 2.4.0

before_script:
  - npm i -g gulp-cli
  - npm install
  - gem install bundler
  - bundle install

script:
  - gulp build-clean  --production 
